freebsd_instance:
  image_family: freebsd-13-0

task:
  name: CI / build

  install_script:
    - pkg install -y python39
    - python3.9 -m venv .venv
    - . .venv/bin/activate && pip install poetry && poetry install --no-root --no-interaction
    - pip list

  script:
    - . .venv/bin/activate && pytest -vv -s --durations=20 --log-cli-level=DEBUG
