# Cirrus CI Configuration

freebsd_task:
  name: CI / build

  env:
    # for lsof
    PATH: ${PATH}:/usr/local/sbin
    SHELLOUS_TRACE: all

  matrix:
    - name: FreeBSD 14.2
      freebsd_instance:
        image_family: freebsd-14-2

  install_script:
    - pkg install -y python312 lsof bash
    - python3.12 -m venv .venv
    - . .venv/bin/activate && pip install -U pip setuptools wheel && pip install -r ./ci/requirements-dev.txt
    # We need to enable the /dev/fd file system on FreeBSD.
    - mount -t fdescfs null /dev/fd

  script:
    - . .venv/bin/activate && pytest -vv -s --durations=20 --log-cli-level=DEBUG
