# Cirrus CI Configuration

freebsd_task:
  name: CI / build

  env:
    # for lsof
    PATH: ${PATH}:/usr/local/sbin
    SHELLOUS_TRACE: all

  matrix:
    - name: FreeBSD 14.0
      freebsd_instance:
        image_family: freebsd-14-0
    - name: FreeBSD 13.3
      freebsd_instance:
        image_family: freebsd-13-3

  install_script:
    - pkg install -y python311 lsof bash
    - python3.11 -m venv .venv
    - . .venv/bin/activate && pip install -U pip setuptools wheel && pip install -r ./ci/requirements-dev.txt
    # We need to enable the /dev/fd file system on FreeBSD.
    - mount -t fdescfs null /dev/fd

  script:
    - . .venv/bin/activate && pytest -vv -s --durations=20 --log-cli-level=DEBUG

  defaultcw_script:
    # Test DefaultChildWatcher.
    - . .venv/bin/activate && SHELLOUS_CHILDWATCHER_TYPE=default pytest -vv -s --durations=20 --log-cli-level=DEBUG | ./ci/annotate.awk -v step=DefaultChildWatcher
