freebsd_instance:
  image_family: freebsd-13-0

task:
  name: CI / build

  install_script:
    - pkg install -y python39
    - python3.9 -m venv .venv
    - . .venv/bin/activate && pip install poetry && poetry install --no-root --no-interaction
    # We need to enable the /dev/fd file system on FreeBSD.
    - mount -t fdescfs null /dev/fd

  script:
    - . .venv/bin/activate && pytest -vv -s --durations=20 --log-cli-level=DEBUG

  safecw_script:
    # Test SafeChildWatcher.
    - . .venv/bin/activate && SHELLOUS_CHILDWATCHER_TYPE=safe pytest -vv -s --durations=20 --log-cli-level=DEBUG

  multicw_script:
    # Test MultiLoopChildWatcher.
    - . .venv/bin/activate && SHELLOUS_CHILDWATCHER_TYPE=multi pytest -vv -s --durations=20 --log-cli-level=DEBUG
