# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches: [ "*" ]
  schedule:
    # Every day at 2:02.
    - cron: '2 2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10  # stop runaway job after 10 minutes
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-11, windows-latest ]
        python-version: [ '3.9', '3.10' ]

    env:
      POETRY_RUN: python -m poetry run
      SHELLOUS_DEBUG: 1
      BUILD_NAME: build (${{ matrix.os }},${{ matrix.python-version }})

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Install poetry and use it to install dependencies.
        python -m pip install poetry
        python -m poetry install --no-root --no-interaction
        if [ "${{ matrix.os }}" != "windows-latest" ]; then
            python -m poetry add uvloop
        fi
    - name: Lint
      run: |
        # Run flake8 and pylint.
        # stop the build if there are Python syntax errors or undefined names
        echo "flake8 preflight:" `$POETRY_RUN flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics`
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        echo "flake8 syntax check:" `$POETRY_RUN flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics`
        $POETRY_RUN pylint -v --fail-under 9.5 shellous
        # Run pylint on tests directory with some checks disabled.
        $POETRY_RUN pylint --disable=C0116,C0103,R0903,W0212,C0302 --fail-under 9.5 tests
        if ! $POETRY_RUN mypy shellous tests; then
          echo "::warning title=Lint Warning::mypy found issues in $BUILD_NAME"
        fi
    - name: Run Tests
      run: |
        if ! $POETRY_RUN python -m pytest -vv -s --durations=20 --log-cli-level=DEBUG | ./ci/annotate.awk; then
          echo "::warning title=Run Tests Warning::Re-running failed tests in $BUILD_NAME"
          $POETRY_RUN python -m pytest -vv -s --durations=20 --log-cli-level=DEBUG --last-failed
        fi
    - name: Run Code Coverage (Linux and MacOS)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
      run: |
        # Run coverage and upload report to codecov.
        $POETRY_RUN coverage run --source shellous -m pytest
        $POETRY_RUN codecov
      env:
        SHELLOUS_CODE_COVERAGE: 1
    - name: Run Tests with uvloop (Linux and MacOS)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
      run: |
        $POETRY_RUN python -m pytest -vv -s --log-cli-level=DEBUG
      env:
        SHELLOUS_LOOP_TYPE: "uvloop"
    - name: Run Tests with PidfdWatcher (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        $POETRY_RUN python -m pytest -vv -s --log-cli-level=DEBUG
      env:
        SHELLOUS_CHILDWATCHER_TYPE: "pidfd"
    - name: Run Tests with SafeChildWatcher (Linux and MacOS)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
      run: |
        $POETRY_RUN python -m pytest -vv -s --log-cli-level=DEBUG
      env:
        SHELLOUS_CHILDWATCHER_TYPE: "safe"
    - name: Run Tests with MultiLoopChildWatcher (Linux and MacOS)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-11'
      run: |
        if ! $POETRY_RUN python -m pytest -vv -s --log-cli-level=DEBUG; then
          echo "::warning title=MultiLoopChildWatcher Warning::Re-running failed tests in $BUILD_NAME"
          $POETRY_RUN python -m pytest -vv -s --log-cli-level=DEBUG --last-failed
        fi
      env:
        SHELLOUS_CHILDWATCHER_TYPE: "multi"
    - name: Run Tests with DefaultChildWatcher (MacOS)
      if: matrix.os == 'macos-11'
      run: |
        # Limit to 5 failures for now because GH actions is auto-cancelling...
        $POETRY_RUN python -m pytest -vv -s --log-cli-level=DEBUG --maxfail=5
      env:
        SHELLOUS_CHILDWATCHER_TYPE: "default"
