name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:

  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Set up python-3.9
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --require-hashes --upgrade setuptools wheel
          python3 -m pip install --require-hashes poetry
      - name: Build package
        run: |
          # Delete lines in README.md that match "__REL_LINK__".
          sed -e '/__REL_LINK__/d' --in-place README.md
          python3 -m poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e # release/v1
        with:
          user: __token__
          password: ${{ secrets.SHELLOUS_PYPI_API_TOKEN }}
          verbose: true
