name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:

  build-package:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Poetry
        run: |
          pipx install poetry==2.1.2
      - name: Build package
        run: |
          poetry --version
          poetry build
      - name: Upload packages
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: package_dists
          path: dist/

  publish-package:
    runs-on: ubuntu-24.04
    needs: build-package
    environment: pypi
    permissions:
      # mandatory for trusted publishing
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit
      - name: Download packages
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: package_dists
          path: dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        with:
          verbose: true
          print-hash: true
