name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:

  publish-package:
    runs-on: ubuntu-22.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
      - name: Build package
        run: |
          # Delete lines in README.md that match "__REL_LINK__".
          sed -e '/__REL_LINK__/d' --in-place README.md
          poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e # release/v1
        with:
          user: __token__
          password: ${{ secrets.SHELLOUS_PYPI_API_TOKEN }}
          verbose: true
          print-hash: true
