name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:

  build-package:
    runs-on: ubuntu-22.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Poetry
        run: |
          pipx install poetry==1.7.1
      - name: Build package
        run: |
          poetry --version
          poetry build
      - name: Upload packages
        uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v4.1.0
        with:
          name: package_dists
          path: dist/

  publish-package:
    runs-on: ubuntu-22.04
    needs: build-package
    environment: pypi
    permissions:
      # mandatory for trusted publishing
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Download packages
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: package_dists
          path: dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # release/v1
        with:
          verbose: true
          print-hash: true
