name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:

  build-package:
    runs-on: ubuntu-22.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install Poetry
        run: |
          pipx install poetry==1.7.1
      - name: Build package
        run: |
          poetry --version
          poetry build
      - name: Upload packages
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        with:
          name: package_dists
          path: dist/

  publish-package:
    runs-on: ubuntu-22.04
    needs: build-package
    environment: pypi
    permissions:
      # mandatory for trusted publishing
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit
      - name: Download packages
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: package_dists
          path: dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0 # release/v1
        with:
          verbose: true
          print-hash: true
