name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:

  build-package:
    runs-on: ubuntu-22.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Install Poetry
        run: |
          pipx install poetry==1.7.1
      - name: Build package
        run: |
          poetry --version
          poetry build
      - name: Upload packages
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: package_dists
          path: dist/

  publish-package:
    runs-on: ubuntu-22.04
    needs: build-package
    environment: pypi
    permissions:
      # mandatory for trusted publishing
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: Download packages
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: package_dists
          path: dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # release/v1
        with:
          verbose: true
          print-hash: true
