name: spellcheck

on:
  push:
    branches: [ "*" ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          strict: false
          incremental_files_only: false
