name: spellcheck

on:
  push:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  spellcheck:
    permissions:
      contents: read  # for streetsidesoftware/cspell-action to fetch files for commit
      pull-requests: read  # for streetsidesoftware/cspell-action to fetch commits for PR
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: streetsidesoftware/cspell-action@22e32eb3d70acf30e3fc09bd46edc1d30fb2d6db # v3.1.0
        with:
          files: |
            **/*.{py,md}
          strict: false
          incremental_files_only: false
          inline: none  # just log misspelled words; no warnings
